name: Finalize feature

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  finalize:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Create Release
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v$(cat VERSION)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
